name: Build and deploy to github page

on: 
  push: 
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          persist-credentials: false
      
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
    
      - name: Deploy to GitHub Page
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
